// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutorunTurnController from "./autorun_turn_controller"
application.register("autorun-turn", AutorunTurnController)

import DialogueController from "./dialogue_controller"
application.register("dialogue", DialogueController)

import GameTimerController from "./game_timer_controller"
application.register("game-timer", GameTimerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TurboFetchController from "./turbo_fetch_controller"
application.register("turbo-fetch", TurboFetchController)

import ServiceWorkerController from "./service_worker_controller"
application.register("service-worker", ServiceWorkerController)
